### PR TITLE
Update VOTING_MEMBERS.md

### PR DESCRIPTION
**Pull request by OlexandrStepanov**
Add myself to the voting members
https://github.com/maplibre/maplibre/issues/36

### CODE REVIEW

**Comment by OlexandrStepanov** [comment]
@wipfli , done.

**Review by wipfli — APPROVED** [review]
Great, welcome @OlexandrStepanov!

**Comment by wipfli** [comment]
And congrats on being the 30th MapLibre Voting Member :)

**Comment by OlexandrStepanov** [comment]
@wipfli , thank you!

**Pull request merged**
