### PR TITLE
Add @jutaz to voting members

### PR DESCRIPTION
**Pull request by jutaz**
Added myself as per #36 invitation

### CODE REVIEW

**Comment by wipfli** [comment]
Great thanks @jutaz Congrats on being the first one!

**Comment by wipfli** [comment]
Please move yourself to the top of the list, such that we keep the alphabetic order...

**Comment by HarelM** [comment]
Beat me to it :-)

**Comment by jutaz** [comment]
> Please move yourself to the top of the list, such that we keep the alphabetic order...

Whoooops. Done!

**Review by wipfli — APPROVED** [review]
Juhuu!

**Pull request merged**
